# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "CI_CD" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Wait for MongoDB to be ready
        run:|
          for i in {1..30}; do
            if mongo --eval "print(\"waited for connection\")"; then
              break
            fi
            echo "MongoDB is starting up..."
            sleep 1
          done
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
          echo "TZ=UTC" >> .env
          echo "PORT=8000" >> .env
          echo "HOST=localhost" >> .env
          echo "LOG_LEVEL=info" >> .env
          echo "NODE_ENV=development" >> .env
          echo "SESSION_DRIVER=cookie" >> .env
          echo "MONGO_URI=mongodb://localhost:27017/citium" >> .env
          echo "JWT_SECRET=$(openssl rand -base64 32)" >> .env
    - run: npm ci
    - run: node ace generate:key
    - run: node ace test
